### ISSUE TITLE
No End of line on test case while importing excel to testlink

### ISSUE THREAD

**Issue by Abaoubida** [MrBricodage/TestLink--ExcelMacros#19]
Great work man.
I have just one issue. when i export test cases from excel to Testlink. the macro doesn't format test cases. all the content of the test case is in the same line (no End of line).

**Comment by MrBricodage** [comment]
I just tested with testlink 1.9.17 and carriage returns are OK. 
What is your test case editor in testlink configuration?

**Comment by Abaoubida** [comment]
Hi,

Thanks for the reply, I work with Testlink 1.9.16

Here is some details about my problem:

on Excel file, i have a step with 3 lines

[image: Images intégrées 1]

when i genearte  Xml file, there is no <p> or <br/> tags

[image: Images intégrées 2]

Finally, when i import the xml file on Testlink, i have the following
result:

[image: Images intégrées 3]

Best Regards;
Anas


2017-05-29 15:00 GMT+00:00 Bob Le Bricodeur <notifications@github.com>:

**Comment by MrBricodage** [comment]
OK, I can't see your attachments but I think that I've understood your problem : your TestLink instance is configured to use an advanced editor (ckeditor or fckeditor). 

Provided macros don't handle HTML tags during import/export, because it's very hard to know if HTML tags are from editor or in TestCase content.

TestLink editor should be forced to 'none' (see provided documentation to know how to do it). 

An other way is to adapt the provided macros to handle HTML tags, but I don't support this feature, you'll have to fork this repo.

regards

Mr.B
